env:
  global:
    - DISPLAY=:99.0
    - PORT_MAP="-p 4000:8888"
    - BASEURL=http://declarativewidgets.org:4000
    - BROWSER_LIST="chrome firefox safari InternetExplorer"

sudo: required

language: node_js

node_js:
  - "4.1"

services:
  - docker

addons:
  firefox: "46.0"
  sauce_connect:
    no_ssl_bump_domains: all
  hosts:
    - declarativewidgets.org

before_script:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sh -e /etc/init.d/xvfb start

script:
  - make all

deploy:
  skip_cleanup: true
  provider: script
  script: make release
  on:
    tags: true

notifications:
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4#jupyter-declwidgets
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
    - DisableAutoSave
    - /^0\.6\.0\.dev[0-9]+$/
